### ISSUE TITLE
Could you merge my changes?

### ISSUE THREAD

**Issue by makinoshi** [malesch/semantic-reagent#1]
Hello,

I have written [these changes](https://github.com/toyokumo/semantic-reagent) mostly to work with advanced compilation and update library versions.

- [#1](https://github.com/toyokumo/semantic-reagent/pull/1)
- [#2](https://github.com/toyokumo/semantic-reagent/pull/2)
- [#3](https://github.com/toyokumo/semantic-reagent/pull/3)
- [#4](https://github.com/toyokumo/semantic-reagent/pull/4)
- [#5](https://github.com/toyokumo/semantic-reagent/pull/5)

Could you merge these changes if I send PR?

**Comment by malesch** [comment]
Hi Makinoshi

Of course and thank you for your efforts!

**Comment by makinoshi** [comment]
@malesch Thank you! I've send #2

**Comment by malesch** [comment]
Hi Makinoshi
Thanks again for the update. 
You dropped the boot support but I think going on with Leiningen makes sense as the boot plugin seem not to be supported as well anymore.
