### ISSUE TITLE
input change causes full-render

### ISSUE THREAD

**Issue by henryw374** [malesch/semantic-reagent#4]
I don't think this is an issue caused by this library, more that reagent is maybe not compatible with semantic-ui-react.

At first glance, this component appears to work, but after a key press the input itself re-renders, causing the caret to move to the end. so for example if i enter 'aaaaa' and then place the caret somewhere in the middle of that and press b a few times, I get 'aabaaabbbb'. After the first b, the re-render causes the caret to lose position.

`
(defn input []
  (reagent.core/with-let [state (reagent.core/atom "")]
    [sui/Input {:value     @state
                :on-change (fn [_ v]
                             (reset! state v.value))}]))`

As I say I don't think the problem is this library. I would guess it is something to do with this https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/ModernAutoControlledComponent.js , but in case you have a workaround I'd be interested to hear. thanks

**Comment by malesch** [comment]
Hi Henry

Haven't had my fingers on this stuff for a while but quicky googled around and found this:

https://github.com/madvas/cljs-react-material-ui/issues/17

https://github.com/reagent-project/reagent/blob/c214466bbcf099eafdfe28ff7cb91f99670a8433/doc/ControlledInputs.md

I quickly tried out with the :default-value attribute and it seems to actually work. ;-)

**Comment by henryw374** [comment]
Thanks very much. I'll give this a try.
